# Generated by Django 5.2 on 2025-06-23 16:32

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('explanation', models.TextField(blank=True, help_text='Пояснение почему ответ правильный/неправильный', null=True, verbose_name='Объяснение ответа')),
            ],
            options={
                'verbose_name': 'ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, verbose_name='URL')),
                ('content', tinymce.models.HTMLField(verbose_name='Содержание')),
                ('video_url', models.URLField(blank=True, help_text='URL видео с YouTube или другого сервиса', null=True, verbose_name='Ссылка на видео')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Длительность (минуты)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('resources', models.FileField(blank=True, null=True, upload_to='lectures/resources/', verbose_name='Дополнительные материалы')),
            ],
            options={
                'verbose_name': 'лекция',
                'verbose_name_plural': 'Лекции',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст вопроса')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Баллы за вопрос')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', tinymce.models.HTMLField(verbose_name='Описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('time_limit', models.PositiveIntegerField(default=30, help_text='Время на прохождение теста в минутах', verbose_name='Лимит времени (минуты)')),
                ('passing_score', models.PositiveIntegerField(default=60, help_text='Минимальный процент для успешного прохождения', verbose_name='Проходной балл (%)')),
            ],
            options={
                'verbose_name': 'тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='Баллы')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершения')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали результатов')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Пройден успешно')),
            ],
            options={
                'verbose_name': 'результат теста',
                'verbose_name_plural': 'Результаты тестов',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='task',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='task',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'permissions': [('can_respond', 'Может отвечать на обращения')], 'verbose_name': 'обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Начинающий'), (2, 'Средний'), (3, 'Продвинутый')], default=1, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Общая продолжительность курса в минутах', verbose_name='Длительность (минуты)'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('bug', 'Ошибка на сайте'), ('suggestion', 'Предложение'), ('question', 'Вопрос'), ('other', 'Другое')], default='question', max_length=50, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ администратора'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа'),
        ),
        migrations.AddField(
            model_name='task',
            name='max_score',
            field=models.PositiveIntegerField(default=10, verbose_name='Максимальный балл'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True, verbose_name='Последний доступ'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки пользователя'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(help_text='Рекомендуемый размер: 1200x600px', upload_to='courses/covers/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='task',
            name='flag',
            field=models.CharField(blank=True, help_text='Флаг в формате FLAG{...}', max_length=200, null=True, verbose_name='Флаг (для CTF)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('quiz', 'Тест'), ('code', 'Код'), ('ctf', 'CTF задание'), ('theory', 'Теоретическое задание')], default='theory', max_length=10, verbose_name='Тип задания'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('difficulty__gte', 1), ('difficulty__lte', 3)), name='difficulty_range'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='core.course', verbose_name='Курс'),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='task',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.lecture', verbose_name='Лекция'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lecture', verbose_name='Лекция'),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'lecture')},
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'completed'], name='core_userpr_user_id_8dcdb8_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gte', 1), ('max_score__lte', 100)), name='max_score_range'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.question', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='test',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.lecture', verbose_name='Лекция'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.test', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='usertestresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.test', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='usertestresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='UserSubmission',
        ),
        migrations.AddConstraint(
            model_name='lecture',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_lecture_order_per_course'),
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('course', 'slug')},
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='task',
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.CheckConstraint(condition=models.Q(('passing_score__gte', 1), ('passing_score__lte', 100)), name='passing_score_range'),
        ),
        migrations.AddIndex(
            model_name='usertestresult',
            index=models.Index(fields=['user', 'test'], name='core_userte_user_id_01345b_idx'),
        ),
    ]
