# Generated by Django 5.2 on 2025-06-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_taskresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskresponse',
            name='answer',
            field=models.TextField(verbose_name='Ответ ученика'),
        ),
    ]
